package mbabski.core;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.time.DayOfWeek;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

public class WriteSubjects {

    public static void writeToFile() {

        List<Subjects> subjects = new ArrayList<>();

        subjects.add(new Subjects("120110-1503", "Badania marketingowe", "Trzebiński Wojciech", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "C-2c", 3.0));
        subjects.add(new Subjects("120480-0389", "Prawo międzynarodowe publiczne", "Menkes Jerzy", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-324", 3.0));
        subjects.add(new Subjects("120490-1227", "Prawo pracy", "Kociołek-Pęksa Anna", DayOfWeek.MONDAY, LocalTime.of(15, 20), "G-232", 3.0));
        subjects.add(new Subjects("120700-1066", "Zarządzanie projektami", "Grucza Bartosz", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "C-1b", 3.0));
        subjects.add(new Subjects("120920-0662", "Marketing międzynarodowy", "Zarzycka Anna M.", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-236", 3.0));
        subjects.add(new Subjects("120921-0301", "International Marketing", "Kowalik Izabela", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "A-210", 3.0));
        subjects.add(new Subjects("121040-0350", "Biznesplan", "Marecki Krzyszof", DayOfWeek.MONDAY, LocalTime.of(8, 00), "G-012 (parter)", 3.0));
        subjects.add(new Subjects("121040-0442", "Biznesplan", "Pawlak Zbigniew", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "G-322", 3.0));
        subjects.add(new Subjects("121110-0470", "Fundusze strukturalne Unii Europejskiej", "Proczek Magdalena", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "G-114", 3.0));
        subjects.add(new Subjects("121390-1066", "Zarządzanie projektami Unii Europejskiej", "Grucza Bartosz", DayOfWeek.THURSDAY, LocalTime.of(17, 10), "C-3b", 3.0));
        subjects.add(new Subjects("121401-0325", "Management in International Business", "Gołębiowski Tomasz", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "Aula B", 3.0));
        subjects.add(new Subjects("121401-0325", "Management in International Business", "Lewandowska Małgorzata", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "Aula B", 3.0));
        subjects.add(new Subjects("121500-0991", "Rynek kapitałowy", "Adamska Agata", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "C-1b", 3.0));
        subjects.add(new Subjects("121500-1888", "Rynek kapitałowy", "Frydrych Sylwia", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "C-4a", 3.0));
        subjects.add(new Subjects("130660-1494", "Prawo podatkowe", "Gajewski Dominik", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "A-1", 3.0));
        subjects.add(new Subjects("210100-0015", "Historia myśli ekonomicznej", "Bartkowiak Ryszard ", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "Aula B", 4.5));
        subjects.add(new Subjects("210100-0104", "Historia myśli ekonomicznej", "Wojciechowska Renata", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "Aula IV", 4.5));
        subjects.add(new Subjects("210100-0241", "Historia myśli ekonomicznej", "Kloc Kazimierz", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "Aula I", 4.5));
        subjects.add(new Subjects("210100-0544", "Historia myśli ekonomicznej", "Sulejewicz Aleksander", DayOfWeek.MONDAY, LocalTime.of(15, 20), "C-Aula I", 4.5));
        subjects.add(new Subjects("210100-0583", "Historia myśli ekonomicznej", "Kightley Marta", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "Aula B", 4.5));
        subjects.add(new Subjects("210100-0658", "Historia myśli ekonomicznej", "Wojciechowska Renata", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "Aula I", 4.5));
        subjects.add(new Subjects("210100-1906", "Historia myśli ekonomicznej", "Korczyk Małgorzata", DayOfWeek.THURSDAY, LocalTime.of(17, 10), "Aula II", 4.5));
        subjects.add(new Subjects("210110-0080", "Prawo gospodarcze", "Czyżowicz Wiesław", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "Aula A", 4.5));
        subjects.add(new Subjects("210110-0153", "Prawo gospodarcze", "Gospodarek Jerzy", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "Aula VI", 4.5));
        subjects.add(new Subjects("210110-0381", "Prawo gospodarcze", "Morawska Sylwia", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "Aula B", 4.5));
        subjects.add(new Subjects("210110-0513", "Prawo gospodarcze", "Siemiątkowski Tomasz", DayOfWeek.TUESDAY, LocalTime.of(8, 00), "Aula I", 4.5));
        subjects.add(new Subjects("210110-1110", "Prawo gospodarcze", "Dominowska Joanna", DayOfWeek.MONDAY, LocalTime.of(15, 20), "Aula II", 4.5));
        subjects.add(new Subjects("210110-1114", "Prawo gospodarcze", "Gwardzińska Ewa", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "Aula II", 4.5));
        subjects.add(new Subjects("210110-1277", "Prawo Gospodarcze", "Boberek Łukasz", DayOfWeek.MONDAY, LocalTime.of(19, 00), "Aula I", 4.5));
        subjects.add(new Subjects("210110-1489", "Prawo gospodarcze", "Godlewska Małgorzata", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "Aula I", 4.5));
        subjects.add(new Subjects("210110-1494", "Prawo gospodarcze", "Gajewski Dominik", DayOfWeek.FRIDAY, LocalTime.of(9, 50), "Aula I", 4.5));
        subjects.add(new Subjects("210130-0159", "Ekonomia", "Grądalski Feliks", DayOfWeek.THURSDAY, LocalTime.of(8, 00), "Aula B", 3.0));
        subjects.add(new Subjects("220281-0301", "International Marketing", "Kowalik Izabela", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "A-210", 3.0));
        subjects.add(new Subjects("220340-0166", "Mikroekonometria", "Gruszczyński Marek", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "C-2b", 3.0));
        subjects.add(new Subjects("220341-1543", "Microeconometrics", "Talarski Marek", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "C-4a", 3.0));
        subjects.add(new Subjects("220380-0450", "Polityka pieniężna", "Kulpaka Paweł", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "A-102", 3.0));
        subjects.add(new Subjects("220380-0493", "Polityka pieniężna", "Rosati Dariusz", DayOfWeek.MONDAY, LocalTime.of(9, 50), "C-Aula I", 3.0));
        subjects.add(new Subjects("220380-0519", "Polityka pieniężna", "Sławiński Andrzej", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-322", 3.0));
        subjects.add(new Subjects("220430-0092", "Portfel inwestycyjny", "Liberadzki Kamil", DayOfWeek.TUESDAY, LocalTime.of(19, 00), "C-1b", 4.5));
        subjects.add(new Subjects("220430-0972", "Portfel inwestycyjny", "Czapiewski Piotr", DayOfWeek.MONDAY, LocalTime.of(19, 00), "C-4b", 4.5));
        subjects.add(new Subjects("220430-1254", "Portfel inwestycyjny", "Bańbuła Piotr", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "G-210 CNJO", 4.5));
        subjects.add(new Subjects("220430-1513", "Portfel inwestycyjny", "Grygiel-Tomaszewska Anna", DayOfWeek.MONDAY, LocalTime.of(17, 10), "G-230", 4.5));
        subjects.add(new Subjects("220431-1156", "Investment portfolio", "Orzechowski Arkadiusz", DayOfWeek.WEDNESDAY, LocalTime.of(8, 00), "G-107", 3.0));
        subjects.add(new Subjects("220440-0035", "Postępowanie nabywców na rynku", "Bombol Małgorzata ", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "G-324", 3.0));
        subjects.add(new Subjects("220440-0385", "Postępowanie nabywców na rynku", "Mróz Bogdan", DayOfWeek.MONDAY, LocalTime.of(11, 40), "G-316", 3.0));
        subjects.add(new Subjects("220441-0035", "Customer Behavior", "Bombol Małgorzata ", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "G-324", 3.0));
        subjects.add(new Subjects("220501-0637", "Entrepreneurship", "Wojtysiak-Kotlarski Marcin", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "C-1b", 3.0));
        subjects.add(new Subjects("220530-0350", "Rachunkowość zarządcza", "Marecki Krzyszof", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "A-107", 3.0));
        subjects.add(new Subjects("220530-0441", "Rachunkowość zarządcza", "Paszula Małgorzata", DayOfWeek.MONDAY, LocalTime.of(11, 40), "C-3a", 3.0));
        subjects.add(new Subjects("220530-0705", "Rachunkowość zarządcza", "Krysik Małgorzata", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "Aula I", 3.0));
        subjects.add(new Subjects("220530-0919", "Rachunkowość zarządcza", "Pielaszek Marcin", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "Aula I", 3.0));
        subjects.add(new Subjects("220570-0438", "Statystyczne metody wielowymiarowej analizy", "Panek Tomasz", DayOfWeek.MONDAY, LocalTime.of(11, 40), "C-3b", 3.0));
        subjects.add(new Subjects("220570-0854", "Statystyczne metody wielowymiarowej analizy", "Podogrodzka Małgorzata", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "C-3d komp.", 3.0));
        subjects.add(new Subjects("220570-0854", "Statystyczne metody wielowymiarowej analizy", "Podogrodzka Małgorzata", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "C-3d komp.", 3.0));
        subjects.add(new Subjects("220570-0854", "Statystyczne metody wielowymiarowej analizy", "Podogrodzka Małgorzata", DayOfWeek.FRIDAY, LocalTime.of(17, 10), "C-3d komp.", 3.0));
        subjects.add(new Subjects("220590-0438", "Statystyka społeczna", "Panek Tomasz", DayOfWeek.MONDAY, LocalTime.of(9, 50), "Aula VII", 3.0));
        subjects.add(new Subjects("220620-0421", "Sztuczna inteligencja", "Olejniczak Jarosław", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "C-1A", 3.0));
        subjects.add(new Subjects("220680-0251", "Ubezpieczenia społeczne", "Cichowicz Ewa", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "G-233", 3.0));
        subjects.add(new Subjects("220740-0060", "Zaawansowana rachunkowość finansowa", "Bareja Katarzyna ", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "C-2a", 4.5));
        subjects.add(new Subjects("220740-0606", "Zaawansowana rachunkowość finansowa", "Tłaczała Agnieszka", DayOfWeek.THURSDAY, LocalTime.of(11, 40), "G-105", 4.5));
        subjects.add(new Subjects("220740-1064", "Zaawansowana rachunkowość finansowa", "Grabowski Rafał", DayOfWeek.MONDAY, LocalTime.of(13, 30), "Aula A", 4.5));
        subjects.add(new Subjects("220741-0060", "Advanced Financial Accounting", "Bareja Katarzyna ", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "C-2a", 3.0));
        subjects.add(new Subjects("220750-0195", "Zarządzanie bankiem", "Iwanicz-Drozdowska Małgorzata", DayOfWeek.MONDAY, LocalTime.of(11, 40), "G-012 (parter)", 4.5));
        subjects.add(new Subjects("220750-0660", "Zarządzanie bankiem", "Zaleska Małgorzata", DayOfWeek.FRIDAY, LocalTime.of(8, 00), "Aula VII", 4.5));
        subjects.add(new Subjects("220751-0195", "Bank management", "Iwanicz-Drozdowska Małgorzata", DayOfWeek.MONDAY, LocalTime.of(9, 50), "Aula B", 3.0));
        subjects.add(new Subjects("220755-1001", "Zarządzanie bankiem (blended learning)", "Bieć Alfred", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-230", 3.0));
        subjects.add(new Subjects("220770-0040", "Zarządzanie logistyczne", "Brdulak Halina ", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "C-1A", 3.0));
        subjects.add(new Subjects("220770-0498", "Zarządzanie logistyczne", "Rutkowski Krzysztof", DayOfWeek.WEDNESDAY, LocalTime.of(8, 00), "C-2b", 3.0));
        subjects.add(new Subjects("220771-0072", "Logistics Management", "Cichosz Marzenna", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "C-1A", 3.0));
        subjects.add(new Subjects("220820-0731", "Zarządzanie wartością przedsiębiorstwa", "Masiukiewicz Piotr", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "G-322", 3.0));
        subjects.add(new Subjects("220820-1013", "Zarządzanie wartością przedsiębiorstwa", "Mikołajek-Gocejna Magdalena", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "A-9", 3.0));
        subjects.add(new Subjects("220820-1595", "Zarządzanie wartością przedsiębiorstwa", "Strojny Mariusz", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "A-219", 3.0));
        subjects.add(new Subjects("220960-0646", "Postępowanie sądowo-administracyjne", "Werner Aleksander", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "G-216 CNJO", 3.0));
        subjects.add(new Subjects("221330-1229", "Międzynarodowe finanse przedsiębiorstw", "Gębski Łukasz", DayOfWeek.MONDAY, LocalTime.of(8, 00), "Aula I", 3.0));
        subjects.add(new Subjects("221331-1427", "International Corporate Finance", "Chmielewska Anna ", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "A-216", 3.0));
        subjects.add(new Subjects("221340-0398", "Globalizacja i regionalizacja w stosunkach międzyn", "Niedziólka Dorota", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "A-210", 3.0));
        subjects.add(new Subjects("221370-0007", "Kulturowe uwarunkowania biznesu międzynarodowego", "Aniszewska-Banaś Grażyna ", DayOfWeek.THURSDAY, LocalTime.of(11, 40), "Aula I", 3.0));
        subjects.add(new Subjects("221470-0161", "Zarządzanie operacyjne", "Gregorczyk Sylwester", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "C-4c", 3.0));
        subjects.add(new Subjects("221470-0174", "Zarządzanie operacyjne", "Godlewska-Majkowska Hanna", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "A-211", 3.0));
        subjects.add(new Subjects("221471-0314", "Operations Management", "Leśniak-Łebkowska Grażyna", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "Aula VII", 3.0));
        subjects.add(new Subjects("221471-0971", "Operations Management", "Bartoszczuk Paweł", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-105", 3.0));
        subjects.add(new Subjects("221480-1287", "Metody statystyczne II", "Zwierzchowski Jan", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "B-12 komp.(Biblioteka)", 3.0));
        subjects.add(new Subjects("221480-1287", "Metody statystyczne II", "Zwierzchowski Jan", DayOfWeek.FRIDAY, LocalTime.of(17, 10), "B-12 komp.(Biblioteka)", 3.0));
        subjects.add(new Subjects("221481-1274", "Statistical Methods II (QEM)", "Rynko Maja", DayOfWeek.TUESDAY, LocalTime.of(8, 00), "A-113 komp.", 3.0));
        subjects.add(new Subjects("221640-0040", "Technologiczne uwarunkowania biznesu międzynarodoweg", "Brdulak Halina ", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "Aula I", 3.0));
        subjects.add(new Subjects("221650-0389", "Instytucjonalne uwarunkowania biznesu międzynarodowe", "Menkes Jerzy", DayOfWeek.FRIDAY, LocalTime.of(9, 50), "Aula VII", 3.0));
        subjects.add(new Subjects("222000-0238", "Algebra i analiza matematyczna", "Kłopotowski Jacek", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "Aula A", 3.0));
        subjects.add(new Subjects("222040-0548", "Ekonometria finansowa I", "Syczewska Ewa", DayOfWeek.THURSDAY, LocalTime.of(17, 10), "Aula Główna", 3.0));
        subjects.add(new Subjects("222041-0291", "Financial Econometrics I", "Krysiak Zbigniew", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "C-2b", 3.0));
        subjects.add(new Subjects("222060-0621", "Ekonometria szeregów czasowych", "Welfe Aleksander", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "G-112", 3.0));
        subjects.add(new Subjects("222080-0012", "Ekonomia instytucjonalna", "Balcerowicz Leszek ", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "A-9", 3.0));
        subjects.add(new Subjects("222080-0100", "Ekonomia instytucjonalna", "Dołęgowski Tomasz", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "C-Aula II", 3.0));
        subjects.add(new Subjects("222080-0578", "Ekonomia instytucjonalna", "Słomka-Gołębiowska Agnieszka", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "Aula B", 3.0));
        subjects.add(new Subjects("222080-0583", "Ekonomia instytucjonalna", "Kightley Marta", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "Aula B", 3.0));
        subjects.add(new Subjects("222080-0802", "Ekonomia instytucjonalna", "Chrzanowski Marek", DayOfWeek.TUESDAY, LocalTime.of(19, 00), "Aula III", 3.0));
        subjects.add(new Subjects("222080-1025", "Ekonomia instytucjonalna", "Bentkowska Katarzyna", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "G-231", 3.0));
        subjects.add(new Subjects("222080-1517", "Ekonomia instytucjonalna", "Skrzek-Lubasińska Małgorzata ", DayOfWeek.THURSDAY, LocalTime.of(11, 40), "Aula B", 3.0));
        subjects.add(new Subjects("222089-1025", "Ekonomia instytucjonalna", "Bentkowska Katarzyna", DayOfWeek.SUNDAY, LocalTime.of(9, 50), "", 3.0));
        subjects.add(new Subjects("222090-0019", "Ekonomia menedżerska", "Bem Dorota ", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "Aula V", 4.5));
        subjects.add(new Subjects("222090-0096", "Ekonomia menedżerska", "Dąbrowski Ireneusz", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "Aula A", 4.5));
        subjects.add(new Subjects("222090-0402", "Ekonomia menedżerska", "Nojszewska Ewelina", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "Aula VI", 4.5));
        subjects.add(new Subjects("222090-0471", "Ekonomia menedżerska", "Prokop Jacek", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "Aula IV", 4.5));
        subjects.add(new Subjects("222090-0479", "Ekonomia menedżerska", "Próchniak Mariusz", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "Aula B", 4.5));
        subjects.add(new Subjects("222090-0689", "Ekonomia menedżerska", "Mokrogulski Mateusz", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "Aula II", 4.5));
        subjects.add(new Subjects("222090-0689", "Ekonomia menedżerska", "Mokrogulski Mateusz", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "Aula II", 4.5));
        subjects.add(new Subjects("222090-0707", "Ekonomia menedżerska", "Maszczyk Piotr", DayOfWeek.TUESDAY, LocalTime.of(9, 50), "Aula I", 4.5));
        subjects.add(new Subjects("222100-0676", "Ekonomia międzynarodowa (zaawansowana)", "Żukrowska Katarzyna", DayOfWeek.FRIDAY, LocalTime.of(9, 50), "Aula II", 3.0));
        subjects.add(new Subjects("222110-0154", "Ekonomia pracy", "Góra Marek", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "Aula III", 3.0));
        subjects.add(new Subjects("222110-0988", "Ekonomia pracy", "Chmielewiec Beata", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "Aula VI", 3.0));
        subjects.add(new Subjects("222110-1107", "Ekonomia pracy", "Wojciechowski Wiktor", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "A-9", 3.0));
        subjects.add(new Subjects("222110-1140", "Ekonomia pracy", "Ruzik-Sierdzińska Anna", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "G-012 (parter)", 3.0));
        subjects.add(new Subjects("222110-1186", "Ekonomia pracy", "Magda Iga", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "G-316", 3.0));
        subjects.add(new Subjects("222110-1295", "Ekonomia pracy", "Guzikowski Mateusz", DayOfWeek.MONDAY, LocalTime.of(19, 00), "Aula IV", 3.0));
        subjects.add(new Subjects("222110-1792", "Ekonomia pracy", "Gałecka-Burdziak Ewa", DayOfWeek.MONDAY, LocalTime.of(13, 30), "G-107", 3.0));
        subjects.add(new Subjects("222120-0015", "Ekonomia rozwoju", "Bartkowiak Ryszard ", DayOfWeek.FRIDAY, LocalTime.of(9, 50), "Aula B", 4.5));
        subjects.add(new Subjects("222120-0132", "Ekonomia rozwoju", "Falkowski Krzysztof", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "Aula V", 4.5));
        subjects.add(new Subjects("222120-0206", "Ekonomia rozwoju", "Jarosiński Krzysztof", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "Aula V", 4.5));
        subjects.add(new Subjects("222120-0309", "Ekonomia rozwoju", "Latoszek Ewa", DayOfWeek.FRIDAY, LocalTime.of(9, 50), "Aula Główna", 4.5));
        subjects.add(new Subjects("222120-0398", "Ekonomia rozwoju", "Niedziólka Dorota", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "Aula Główna", 4.5));
        subjects.add(new Subjects("222120-0398", "Ekonomia rozwoju", "Niedziólka Dorota", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "Aula VI", 4.5));
        subjects.add(new Subjects("222120-0398", "Ekonomia rozwoju", "Niedziólka Dorota", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "C-Aula I", 4.5));
        subjects.add(new Subjects("222120-0581", "Ekonomia rozwoju", "Słobodzian Ludmiła", DayOfWeek.THURSDAY, LocalTime.of(17, 10), "Aula V", 4.5));
        subjects.add(new Subjects("222120-0712", "Ekonomia rozwoju", "Bołkunow Wiktor", DayOfWeek.FRIDAY, LocalTime.of(9, 50), "C-1b", 4.5));
        subjects.add(new Subjects("222130-0119", "Ekonomia sektora publicznego", "Dzierżek Lidia", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "Aula III", 4.5));
        subjects.add(new Subjects("222130-0206", "Ekonomia sektora publicznego", "Jarosiński Krzysztof", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "Aula V", 4.5));
        subjects.add(new Subjects("222130-0402", "Ekonomia sektora publicznego", "Nojszewska Ewelina", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "Aula V", 4.5));
        subjects.add(new Subjects("222130-1097", "Ekonomia sektora publicznego", "Ciżkowicz Piotr", DayOfWeek.THURSDAY, LocalTime.of(17, 10), "Aula I", 4.5));
        subjects.add(new Subjects("222130-1581", "Ekonomia sektora publicznego", "Sadowy Katarzyna", DayOfWeek.FRIDAY, LocalTime.of(17, 10), "Aula III", 4.5));
        subjects.add(new Subjects("222140-0257", "Ekonomia środowiska", "Korporowicz Violetta", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "G-111", 3.0));
        subjects.add(new Subjects("222151-0999", "Mathematical economics and optimal control theory", "Growiec Jakub", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "C-1A", 3.0));
        subjects.add(new Subjects("222160-0100", "Etyka w biznesie", "Dołęgowski Tomasz", DayOfWeek.MONDAY, LocalTime.of(15, 20), "C-2a", 3.0));
        subjects.add(new Subjects("222160-0218", "Etyka w biznesie", "Jastrzębska Ewa Magdalena", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "A-9", 3.0));
        subjects.add(new Subjects("222160-0385", "Etyka w biznesie", "Mróz Bogdan", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "A-209", 3.0));
        subjects.add(new Subjects("222160-0387", "Etyka w biznesie", "Myśliwiec Grzegorz", DayOfWeek.FRIDAY, LocalTime.of(17, 10), "Aula IV", 3.0));
        subjects.add(new Subjects("222160-0512", "Etyka w biznesie", "Rosiak-Zięba Ewa", DayOfWeek.THURSDAY, LocalTime.of(19, 00), "Aula V", 3.0));
        subjects.add(new Subjects("222160-0566", "Etyka w biznesie", "Szulczewski Grzegorz", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "Aula VI", 3.0));
        subjects.add(new Subjects("222160-0697", "Etyka w biznesie", "Turek Dariusz", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "Aula B", 3.0));
        subjects.add(new Subjects("222160-1017", "Etyka w biznesie", "Klimek Jan", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "Aula III", 3.0));
        subjects.add(new Subjects("222160-1252", "Etyka w biznesie", "Rosiak-Zięba Ewa", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "Aula VII", 3.0));
        subjects.add(new Subjects("222230-0228", "Informacyjne systemy zarządzania", "Kamiński Andrzej", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "C-5e", 3.0));
        subjects.add(new Subjects("222230-1280", "Informacyjne systemy zarządzania", "Filipkowski Piotr", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "C-4a", 3.0));
        subjects.add(new Subjects("222250-0291", "Inżynieria finansowa", "Krysiak Zbigniew", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "C-4b", 3.0));
        subjects.add(new Subjects("222250-0998", "Inżynieria finansowa", "Pruchnicka -Grabias Izabela", DayOfWeek.WEDNESDAY, LocalTime.of(8, 00), "Aula I", 3.0));
        subjects.add(new Subjects("222250-1254", "Inżynieria finansowa", "Bańbuła Piotr", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "G-210 CNJO", 3.0));
        subjects.add(new Subjects("222260-0243", "Inżynieria oprogramowania", "Kobyliński Andrzej", DayOfWeek.MONDAY, LocalTime.of(13, 30), "A-210", 3.0));
        subjects.add(new Subjects("222291-1126", "Advanced Macroeconomics", "Kolasa Marcin", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "G-110", 3.0));
        subjects.add(new Subjects("222321-1003", "Introduction to Probability Theory and Stochastic Pr", "Kwas Marek", DayOfWeek.MONDAY, LocalTime.of(11, 40), "C-5d komp.", 3.0));
        subjects.add(new Subjects("222340-1152", "Międzynarodowe rynki finansowe", "Waszkiewicz Aneta", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "Aula II", 3.0));
        subjects.add(new Subjects("222370-1248", "Mikroekonomia (zaawansowana)", "Rojek Miłosz", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "G-107", 3.0));
        subjects.add(new Subjects("222371-0089", "Advanced Microeconomics (QEM)", "Woźny Łukasz", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "C-3a", 3.0));
        subjects.add(new Subjects("222451-0006", "Poland in the European Union", "Ambroziak Adam", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "G-111", 3.0));
        subjects.add(new Subjects("222460-0628", "Prawo finansowe i podatkowe", "Wierzbicki Jarosław", DayOfWeek.WEDNESDAY, LocalTime.of(8, 00), "Aula A", 4.5));
        subjects.add(new Subjects("222460-1494", "Prawo finansowe i podatkowe", "Gajewski Dominik", DayOfWeek.FRIDAY, LocalTime.of(14, 25), "Aula A", 4.5));
        subjects.add(new Subjects("222461-0410", "Financial and Tax Law", "Nowak-Far Artur", DayOfWeek.MONDAY, LocalTime.of(10, 45), "G-107", 3.0));
        subjects.add(new Subjects("222470-0153", "Prawo handlowe", "Gospodarek Jerzy", DayOfWeek.FRIDAY, LocalTime.of(17, 10), "Aula VI", 3.0));
        subjects.add(new Subjects("222490-0187", "Rachunek kosztów", "Hellich Ewa", DayOfWeek.WEDNESDAY, LocalTime.of(8, 00), "C-4a", 3.0));
        subjects.add(new Subjects("222490-0705", "Rachunek kosztów", "Krysik Małgorzata", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "Aula I", 3.0));
        subjects.add(new Subjects("222490-0919", "Rachunek kosztów", "Pielaszek Marcin", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "Aula I", 3.0));
        subjects.add(new Subjects("222491-1330", "Cost Accounting (ACCA)", "Raulinajtys-Grzybek Monika", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "G-236", 3.0));
        subjects.add(new Subjects("222580-0098", "Rachunek prawdopodobieństwa i procesy stochastyczn", "Dędys Monika", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "W-36", 3.0));
        subjects.add(new Subjects("222600-0988", "Zarządzanie kapitałem ludzkim", "Chmielewiec Beata", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "G-223", 3.0));
        subjects.add(new Subjects("222610-0161", "Zarządzanie procesami", "Gregorczyk Sylwester", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "C-2a", 3.0));
        subjects.add(new Subjects("222610-1068", "Zarządzanie procesami", "Juchniewicz Mateusz", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "Aula VII", 3.0));
        subjects.add(new Subjects("222620-0030", "Zarządzanie strategiczne", "Błaszczyk Marek ", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "G-230", 3.0));
        subjects.add(new Subjects("222620-0330", "Zarządzanie strategiczne", "Łobejko Stanisław", DayOfWeek.FRIDAY, LocalTime.of(9, 50), "C-4a", 3.0));
        subjects.add(new Subjects("222620-1002", "Zarządzanie strategiczne", "Korpus Joanna", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "C-4a", 3.0));
        subjects.add(new Subjects("222620-1257", "Zarządzanie strategiczne", "Mierzejewska Wioletta", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "G-316", 3.0));
        subjects.add(new Subjects("222621-0004", "Strategic Management", "Aluchna Maria ", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "C-5c", 3.0));
        subjects.add(new Subjects("222800-1358", "Nieklasyczne metody optymalizacj", "Koloch Grzegorz", DayOfWeek.TUESDAY, LocalTime.of(8, 00), "Aula VII", 3.0));
        subjects.add(new Subjects("222810-0350", "Rachunkowość zarządcza i rachunek kosztów", "Marecki Krzyszof", DayOfWeek.MONDAY, LocalTime.of(9, 50), "G-012 (parter)", 3.0));
        subjects.add(new Subjects("222810-0649", "Rachunkowość zarządcza i rachunek kosztów", "Wieloch Maciej", DayOfWeek.MONDAY, LocalTime.of(17, 10), "G-236", 3.0));
        subjects.add(new Subjects("222810-0968", "Rachunkowość zarządcza i rachunek kosztów", "Baran Wioletta", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "Aula II", 3.0));
        subjects.add(new Subjects("222811-1234", "Management and Cost Accounting", "Wierzbicki Rafał", DayOfWeek.MONDAY, LocalTime.of(13, 30), "G-236", 3.0));
        subjects.add(new Subjects("222940-0740", "Teoria gier", "Winnicka Justyna", DayOfWeek.MONDAY, LocalTime.of(15, 20), "A-216", 3.0));
        subjects.add(new Subjects("222950-1247", "Ekonometria przestrzenna", "Torój Andrzej", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-112", 3.0));
        subjects.add(new Subjects("222970-0692", "Teoria zarządzania", "Ornarowicz Urszula", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "C-4b", 3.0));
        subjects.add(new Subjects("222980-0153", "Prawo cywilne", "Gospodarek Jerzy", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "G-107", 3.0));
        subjects.add(new Subjects("222980-1110", "Prawo cywilne", "Dominowska Joanna", DayOfWeek.MONDAY, LocalTime.of(17, 10), "Aula II", 3.0));
        subjects.add(new Subjects("223050-0011", "Makroekonomia zaawansowana I", "Adamowicz Elżbieta ", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "Aula II", 3.0));
        subjects.add(new Subjects("223090-0568", "Big data", "Szupiluk Ryszard", DayOfWeek.MONDAY, LocalTime.of(9, 50), "B-12 komp.(Biblioteka)", 3.0));
        subjects.add(new Subjects("223090-0568", "Big data", "Szupiluk Ryszard", DayOfWeek.MONDAY, LocalTime.of(11, 40), "B-12 komp.(Biblioteka)", 3.0));
        subjects.add(new Subjects("223200-1338", "Dyplomacja gospodarcza", "Nyga-Łukaszewska Honorata ", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "G-111", 3.0));
        subjects.add(new Subjects("223230-0622", "Ekonomia innowacji i zarządzanie innowacjami", "Weresa Marzenna A.", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "G-316", 3.0));
        subjects.add(new Subjects("223240-0047", "Środowisko naturalne i energia: konflikty i współpra", "Budnikowski Adam ", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "Aula IV", 3.0));
        subjects.add(new Subjects("223241-1147", "Natural Environment and Energy: International Confl", "Krysik Damian", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "Aula IV", 3.0));
        subjects.add(new Subjects("223250-1517", "Ekonomia Behawioralna w e-biznesie", "Skrzek-Lubasińska Małgorzata ", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "Aula B", 3.0));
        subjects.add(new Subjects("223260-0284", "Ekonomia niedoskonałej konkurencji", "Knauff Małgorzata", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "A-9", 3.0));
        subjects.add(new Subjects("223270-1280", "Technologie cyfrowe w relacjach gospodarczych", "Filipkowski Piotr", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "Aula VII", 3.0));
        subjects.add(new Subjects("223280-1013", "Finansowanie i wycena spółek technologicznych", "Mikołajek-Gocejna Magdalena", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "Aula B", 3.0));
        subjects.add(new Subjects("223281-0969", "Financing and Valuation of High-Tech Companies", "Roszkowska Paulina", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "C-5c", 3.0));
        subjects.add(new Subjects("223290-0120", "Strategie i modele e-biznesu", "Doligalski Tymoteusz", DayOfWeek.THURSDAY, LocalTime.of(11, 40), "Aula VII", 3.0));
        subjects.add(new Subjects("223310-0465", "Analiza i zastosowania sieci społecznych w interne", "Polańska Krystyna ", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "G-012 (parter)", 3.0));
        subjects.add(new Subjects("223320-0132", "Globalne ubóstwo, niedorozwój i rozwój", "Falkowski Krzysztof", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "Aula Główna", 3.0));
        subjects.add(new Subjects("223350-0080", "Prawo e-biznesu", "Czyżowicz Wiesław", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "Aula Główna", 3.0));
        subjects.add(new Subjects("223350-0080", "Prawo e-biznesu", "Godlewska Małgorzata", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "Aula Główna", 3.0));
        subjects.add(new Subjects("223370-0120", "Nowe technologie w marketingu", "Doligalski Tymoteusz", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "Aula Główna", 3.0));
        subjects.add(new Subjects("223390-0431", "Strategiczne zarządzanie projektami", "Opałka Benedykt", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "C-1b", 3.0));
        subjects.add(new Subjects("223390-1059", "Strategiczne zarządzanie projektami", "Bukłaha Emil", DayOfWeek.THURSDAY, LocalTime.of(17, 10), "C-3a", 3.0));
        subjects.add(new Subjects("223450-0438", "Statystyczne metody analizy ubóstwa, wykluczenia spo", "Panek Tomasz", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "G-235 komp.", 3.0));
        subjects.add(new Subjects("223490-0286", "Statystyczne reguły decyzyjne", "Kamiński Bogumił", DayOfWeek.WEDNESDAY, LocalTime.of(8, 00), "C-1b", 3.0));
        subjects.add(new Subjects("223500-0024", "Zarządzanie finansami na rynku międzynarodowym", "Bień Andrzej ", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "G-105", 3.0));
        subjects.add(new Subjects("223960-1066", "Podstawy zarządzania projektami", "Grucza Bartosz", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "C-1b", 3.0));
        subjects.add(new Subjects("224380-0160", "Efektywne zarządzanie IT w przedsiębiorstwie", "Orzechowski Remigiusz", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "Aula VII", 3.0));
        subjects.add(new Subjects("224390-0723", "Obliczenia i przetwarzanie danych w chmurze-cloud co", "Szufel Przemysław", DayOfWeek.MONDAY, LocalTime.of(11, 40), "C-Aula I", 3.0));
        subjects.add(new Subjects("224410-0952", "Style życia usługi czasu wolnego", "Biernat Elżbieta ", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "G-232", 3.0));
        subjects.add(new Subjects("224410-2845", "Style życia usługi czasu wolnego", "Koskowski Michał", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "G-324", 3.0));
        subjects.add(new Subjects("224520-0651", "Finanse i rachunkowość menedżerska", "Warowny Paweł", DayOfWeek.MONDAY, LocalTime.of(15, 20), "Aula III", 3.0));
        subjects.add(new Subjects("224550-0072", "Logistyka", "Cichosz Marzenna", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "C-2c", 3.0));
        subjects.add(new Subjects("224560-0381", "Prawne uwarunkwania pracy menedżera", "Morawska Sylwia", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "G-316", 3.0));
        subjects.add(new Subjects("225020-1180", "Wprowadzenie do zarządzania projektami", "Wyrozębski Paweł", DayOfWeek.MONDAY, LocalTime.of(15, 20), "C-Aula II", 3.0));
        subjects.add(new Subjects("225050-1330", "Rachunkowość projektów", "Raulinajtys-Grzybek Monika", DayOfWeek.THURSDAY, LocalTime.of(11, 40), "C-1b", 3.0));
        subjects.add(new Subjects("225060-0442", "Podstawy organizacji i zarządzania", "Pawlak Zbigniew", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "C-Aula II", 3.0));
        subjects.add(new Subjects("225110-1180", "Zarządzanie przedsiębiorstwem", "Wyrozębski Paweł", DayOfWeek.MONDAY, LocalTime.of(15, 20), "C-Aula II", 3.0));
        subjects.add(new Subjects("225130-1068", "Zarzadzanie procesami biznesowymi", "Juchniewicz Mateusz", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "Aula VII", 3.0));
        subjects.add(new Subjects("226020-0490", "Analiza aktywności projektów", "Rogowski Waldemar", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "C-1b", 3.0));
        subjects.add(new Subjects("226030-0651", "Controling i audyt finansowy przedsiębiorstwa", "Warowny Paweł", DayOfWeek.MONDAY, LocalTime.of(19, 00), "A-9", 3.0));
        subjects.add(new Subjects("226040-1137", "Diagnostyka finansowa przedsiębiorstwa", "Ciesielska-Maciągowska Dorota", DayOfWeek.MONDAY, LocalTime.of(8, 00), "C-2a", 3.0));
        subjects.add(new Subjects("226060-0171", "Finanse korporacji", "Grzywacz Jacek", DayOfWeek.MONDAY, LocalTime.of(9, 50), "Aula Główna", 3.0));
        subjects.add(new Subjects("226070-0458", "Tradycyjne i alternatywne źródła finansowania przedi", "Podedworna-Tarnowska Dorota", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "G-012 (parter)", 3.0));
        subjects.add(new Subjects("226080-0705", "Rachunkowość finansowa i menedżerska", "Raulinajtys-Grzybek Monika", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "Aula III", 3.0));
        subjects.add(new Subjects("226100-0291", "Zastosowania inżynierii finansowej", "Krysiak Zbigniew", DayOfWeek.MONDAY, LocalTime.of(13, 30), "G-231", 3.0));
        subjects.add(new Subjects("226110-0231", "Zintegrowane zarządzanie ryzykiem - ERM", "Kasiewicz Stanisław", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "A-210", 3.0));
        subjects.add(new Subjects("226150-0637", "Przedsiębiorczość - perspektywa startupu", "Wojtysiak-Kotlarski Marcin", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "C-1b", 3.0));
        subjects.add(new Subjects("226151-1257", "Startup entrepreneurship", "Marecki Dawid", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "C-2c", 3.0));
        subjects.add(new Subjects("230060-0058", "Analiza techniczna i fundamentalna", "Borowski Krzysztof", DayOfWeek.TUESDAY, LocalTime.of(8, 00), "Aula II", 3.0));
        subjects.add(new Subjects("230120-1355", "Komunikacja społeczna", "Konopka Dorota", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "G-223", 3.0));
        subjects.add(new Subjects("230200-1247", "Ekonometria bayesowska", "Torój Andrzej", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "G-112", 3.0));
        subjects.add(new Subjects("230240-1027", "Ekonometryczne modele nieliniowe", "Serwa Dobromił", DayOfWeek.MONDAY, LocalTime.of(8, 00), "C-3e komp.", 3.0));
        subjects.add(new Subjects("230300-0290", "Europejski system transportowy", "Król Marcin", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "C-4c", 3.0));
        subjects.add(new Subjects("230460-0616", "Kierowanie zespołem projektowym", "Wachowiak Piotr", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "A-209", 3.0));
        subjects.add(new Subjects("230460-1066", "Kierowanie zespołem projektowym", "Grucza Bartosz", DayOfWeek.THURSDAY, LocalTime.of(19, 00), "C-3b", 3.0));
        subjects.add(new Subjects("230510-0498", "Logistyka dystrybucji", "Rutkowski Krzysztof", DayOfWeek.WEDNESDAY, LocalTime.of(8, 00), "C-2b", 3.0));
        subjects.add(new Subjects("230540-1178", "Marketing na rynku instytucjonalnym", "Dąbrowski Tomasz", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "C-3c", 3.0));
        subjects.add(new Subjects("230541-1060", "Business-to-Business Marketing", "Danik Lidia", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "A-209", 3.0));
        subjects.add(new Subjects("230541-1060", "Business-to-Business Marketing", "Gołębiowski Tomasz", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "A-209", 3.0));
        subjects.add(new Subjects("230570-0347", "Marketing usług transportowych", "Marciszewska Elżbieta", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "A-8", 3.0));
        subjects.add(new Subjects("230710-0440", "Międzynarodowe rynki transportowe", "Paprocki Wojciech", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "C-5e", 3.0));
        subjects.add(new Subjects("230720-1268", "Modele i prognozy demograficzne", "Strzelecki Paweł", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "C-3e komp.", 3.0));
        subjects.add(new Subjects("230820-1180", "Organizacja projektowa", "Wyrozębski Paweł", DayOfWeek.MONDAY, LocalTime.of(13, 30), "C-5e", 3.0));
        subjects.add(new Subjects("230880-0301", "Podstawy informacyjne marketingu", "Kowalik Izabela", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "G-231", 3.0));
        subjects.add(new Subjects("230910-0348", "Polityka budżetowa", "Marczakowska-Proczka Joanna", DayOfWeek.WEDNESDAY, LocalTime.of(8, 00), "G-223", 3.0));
        subjects.add(new Subjects("231090-1571", "Proces motywowania pracowników", "Kinowska Hanna", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "C-2b", 3.0));
        subjects.add(new Subjects("231150-0627", "Rachunkowość w banku", "Wielgórska-Leszczyńska Joanna", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "C-5b", 3.0));
        subjects.add(new Subjects("231160-0229", "Rachunkowość w zakładzie ubezpieczeń", "Karmańska Anna", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "C-5b", 3.0));
        subjects.add(new Subjects("231170-0366", "Reasekuracja", "Michalski Tomasz", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-216 CNJO", 3.0));
        subjects.add(new Subjects("231210-0526", "Restrukturyzacja przedsiębiorstwa", "Sokół Hanna", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "G-110", 3.0));
        subjects.add(new Subjects("231230-0126", "Rynek instrumentów pochodnych", "Fierla Andrzej", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "G-114", 3.0));
        subjects.add(new Subjects("231230-0367", "Rynek instrumentów pochodnych", "Mielus Piotr", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "G-114", 3.0));
        subjects.add(new Subjects("231231-0345", "Derivatives Market", "Marciniak Zenon", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "C-4b", 3.0));
        subjects.add(new Subjects("231380-0502", "Strategia personalna przedsiębiorstwa", "Rostkowski Tomasz", DayOfWeek.THURSDAY, LocalTime.of(17, 10), "G-233", 3.0));
        subjects.add(new Subjects("231420-0325", "Strategie konkurencji i rozwoju polskich przedsięb", "Lewandowska Małgorzata", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "G-231", 3.0));
        subjects.add(new Subjects("231420-0325", "Strategie konkurencji i rozwoju polskich przedsięb", "Gołębiowski Tomasz", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "G-231", 3.0));
        subjects.add(new Subjects("231450-0639", "Systemy baz danych II", "Wódz Danuta", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "G-322", 3.0));
        subjects.add(new Subjects("231510-1277", "Prawne uwarunkowania prowadzenia własnego biznesu", "Boberek Łukasz", DayOfWeek.MONDAY, LocalTime.of(17, 10), "A-210", 3.0));
        subjects.add(new Subjects("231560-0159", "Teoria opodatkowania", "Grądalski Feliks", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "A-106", 3.0));
        subjects.add(new Subjects("231670-1281", "Konwersatorium z ekonomii", "Karbowski Adam", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "Aula I", 3.0));
        subjects.add(new Subjects("231760-0572", "Marketing dóbr luksusowych i o charakterze symbolic", "Sikora Tomasz", DayOfWeek.TUESDAY, LocalTime.of(19, 00), "G-112", 3.0));
        subjects.add(new Subjects("231880-1021", "Alternatywny pieniądz", "Sobiecki Grzegorz", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "G-225", 3.0));
        subjects.add(new Subjects("232000-0074", "Międzynarodowe strategie kooperacji przedsiębiorst", "Cygler Joanna", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "A-9", 3.0));
        subjects.add(new Subjects("232080-0027", "Techniki aktuarialne w praktyce ubezpieczeń na życie", "Bijak Wojciech ", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "C-3d komp.", 3.0));
        subjects.add(new Subjects("232160-0628", "Postępowanie podatkowe", "Wierzbicki Jarosław", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "Aula A", 3.0));
        subjects.add(new Subjects("232301-1137", "Business Strategies for Central and Eastern Europe", "Ciesielska-Maciągowska Dorota", DayOfWeek.MONDAY, LocalTime.of(9, 50), "C-1b", 3.0));
        subjects.add(new Subjects("232461-0622", "National Innovation Systems in the World Economy", "Weresa Marzenna A.", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "A-9", 3.0));
        subjects.add(new Subjects("232580-0024", "Teoria i polityka kursów walutowych", "Bień Andrzej ", DayOfWeek.THURSDAY, LocalTime.of(11, 40), "Aula IV", 3.0));
        subjects.add(new Subjects("232580-0349", "Teoria i polityka kursów walutowych", "Marczewski Krzysztof", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "G-225", 3.0));
        subjects.add(new Subjects("232600-0030", "Analiza strategiczna przedsiębiorstwa w wymiarze m", "Błaszczyk Marek ", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "G-230", 3.0));
        subjects.add(new Subjects("232650-0604", "Fuzje i przejęcia przedsiębiorstw", "Tuzimek Rafał", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "G-232", 3.0));
        subjects.add(new Subjects("232650-1002", "Fuzje i przejęcia przedsiębiorstw", "Korpus Joanna", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "C-3b", 3.0));
        subjects.add(new Subjects("232650-1229", "Fuzje i przejęcia przedsiębiorstw", "Gębski Łukasz", DayOfWeek.MONDAY, LocalTime.of(9, 50), "Aula I", 3.0));
        subjects.add(new Subjects("232651-0699", "Mergers and Acquisitions of Enterprises", "Radło Mariusz J.", DayOfWeek.WEDNESDAY, LocalTime.of(8, 00), "A-209", 3.0));
        subjects.add(new Subjects("232651-2723", "Mergers and Acquisitions of Enterprises", "Melnarowicz Krzysztof", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "G-112", 3.0));
        subjects.add(new Subjects("232770-0431", "Partnerstwo publiczno-prywatne", "Opałka Benedykt", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "C-5e", 3.0));
        subjects.add(new Subjects("232901-0207", "Strategic Analysis of European Markets", "Jarosiński Mirosław", DayOfWeek.THURSDAY, LocalTime.of(17, 10), "C-2a", 3.0));
        subjects.add(new Subjects("233010-0022", "Analiza koniunktury i badanie rynków zagranicznych", "Bieć Maria", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "A-8", 3.0));
        subjects.add(new Subjects("233030-0444", "Analiza wzorów konsumpcji gospodarstw domowych", "Perek-Białas Jolanta", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "B-12 komp.(Biblioteka)", 3.0));
        subjects.add(new Subjects("233040-0495", "Analizy rynku metodami ilościowymi", "Rószkiewicz Małgorzata", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "C-2d komp.", 3.0));
        subjects.add(new Subjects("233060-0514", "Budżet samorządowy", "Sierak Jacek", DayOfWeek.MONDAY, LocalTime.of(17, 10), "C-5c", 3.0));
        subjects.add(new Subjects("233070-0738", "Business Intelligence", "Surma Jerzy", DayOfWeek.FRIDAY, LocalTime.of(8, 00), "Aula III", 3.0));
        subjects.add(new Subjects("233180-0975", "Ekonometria finansowa II", "Rubaszek Michał", DayOfWeek.THURSDAY, LocalTime.of(8, 00), "G-116 komp.", 3.0));
        subjects.add(new Subjects("233200-1295", "Ekonomia polityczna", "Guzikowski Mateusz", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "G-225", 3.0));
        subjects.add(new Subjects("233240-0662", "Euromarketing", "Zarzycka Anna M.", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "G-236", 3.0));
        subjects.add(new Subjects("233310-0395", "Jakościowe badania marketingowe", "Marciniak Beata", DayOfWeek.THURSDAY, LocalTime.of(8, 00), "C-4b", 3.0));
        subjects.add(new Subjects("233350-0003", "Kryzysy finansowe i stabilność finansowa", "Alińska Agnieszka", DayOfWeek.MONDAY, LocalTime.of(19, 00), "Aula III", 3.0));
        subjects.add(new Subjects("233350-0393", "Kryzysy finansowe i stabilność finansowa", "Matusewicz Michał", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "A-216", 3.0));
        subjects.add(new Subjects("233461-0089", "General Equilibrium Frameworks", "Woźny Łukasz", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "C-5e", 3.0));
        subjects.add(new Subjects("233490-0579", "Optymalizacja podatkowa", "Szlęzak-Matusewicz Joanna", DayOfWeek.MONDAY, LocalTime.of(13, 30), "Aula III", 3.0));
        subjects.add(new Subjects("233490-1109", "Optymalizacja podatkowa", "Jamroży Marcin", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "Aula B", 3.0));
        subjects.add(new Subjects("233510-0170", "Plan zarządzania nieruchomością", "Grzymała Zbigniew", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-224", 3.0));
        subjects.add(new Subjects("233580-1114", "Prawo celne", "Gwardzińska Ewa", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "A-218", 3.0));
        subjects.add(new Subjects("233590-0381", "Prawo karne skarbowe", "Morawska Sylwia", DayOfWeek.FRIDAY, LocalTime.of(17, 10), "G-012 (parter)", 3.0));
        subjects.add(new Subjects("233640-0603", "Problemy demograficzne świata", "Trzcińska Barbara", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "G-112", 3.0));
        subjects.add(new Subjects("233680-0514", "Przygotowanie projektów finansowanych ze środków U", "Sierak Jacek", DayOfWeek.MONDAY, LocalTime.of(19, 00), "C-5c", 3.0));
        subjects.add(new Subjects("233710-0093", "Regulacje i nadzór nad rynkami finansowymi", "Liberadzki Marcin", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "C-3a", 3.0));
        subjects.add(new Subjects("233710-0299", "Regulacje i nadzór nad rynkami finansowymi", "Kluza Stanisław", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "G-114", 3.0));
        subjects.add(new Subjects("233760-1506", "Ryzyko w zakładzie ubezpieczeń", "Janowicz-Lomott Marietta ", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "G-114", 3.0));
        subjects.add(new Subjects("233850-0059", "Statystyka aktuarialna i teoria ryzyka", "Boratyńska Agata ", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-231", 3.0));
        subjects.add(new Subjects("233890-0074", "Strategie kooperacji przedsiębiorstw", "Cygler Joanna", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "A-9", 3.0));
        subjects.add(new Subjects("233910-1138", "Struktura kapitału w przedsiębiorstwie", "Dec Paweł", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "Aula B", 3.0));
        subjects.add(new Subjects("233970-0366", "Teoria ryzyka", "Michalski Tomasz", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "G-216 CNJO", 3.0));
        subjects.add(new Subjects("234040-0972", "Zaawansowana bankowość inwestycyjna", "Czapiewski Piotr", DayOfWeek.WEDNESDAY, LocalTime.of(18, 05), "C-3a", 3.0));
        subjects.add(new Subjects("234041-0995", "Advanced Investment Banking", "Wiśniewski Piotr", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "C-5c", 3.0));
        subjects.add(new Subjects("234060-0723", "Zaawansowane modelowanie symulacyjne", "Szufel Przemysław", DayOfWeek.MONDAY, LocalTime.of(13, 30), "C-Aula I", 3.0));
        subjects.add(new Subjects("234080-0190", "Zarządzanie innowacjami w przedsiębiorstwie", "Pindelski Mikołaj", DayOfWeek.TUESDAY, LocalTime.of(19, 00), "G-111", 3.0));
        subjects.add(new Subjects("234100-1238", "Zarządzanie portfelem kredytowym banku", "Kuszewski Piotr", DayOfWeek.THURSDAY, LocalTime.of(17, 10), "G-110", 3.0));
        subjects.add(new Subjects("234110-1230", "Zarządzanie projektami informatycznymi", "Sońta-Drączkowska Ewa", DayOfWeek.THURSDAY, LocalTime.of(8, 00), "G-108 kom.", 3.0));
        subjects.add(new Subjects("234140-0291", "Zarządzanie ryzykiem finansowym w przedsiębiorstwi", "Krysiak Zbigniew", DayOfWeek.MONDAY, LocalTime.of(8, 00), "G-322", 3.0));
        subjects.add(new Subjects("234140-0526", "Zarządzanie ryzykiem finansowym w przedsiębiorstwi", "Sokół Hanna", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "Aula I", 3.0));
        subjects.add(new Subjects("234141-0291", "Corporate Financial Risk Management", "Krysiak Zbigniew", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "C-2b", 3.0));
        subjects.add(new Subjects("234150-0399", "Zarządzanie ryzykiem rynkowym i operacyjnym", "Niedziółka Paweł", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "G-103", 3.0));
        subjects.add(new Subjects("234301-0387", "Negotiations", "Myśliwiec Grzegorz", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "C-2b", 3.0));
        subjects.add(new Subjects("234490-0291", "Zarządzanie finansami (ACCA-P)", "Krysiak Zbigniew", DayOfWeek.WEDNESDAY, LocalTime.of(14, 25), "C-4b", 3.0));
        subjects.add(new Subjects("234610-0581", "Transformacja systemowa Rosji", "Słobodzian Ludmiła", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "A-103", 3.0));
        subjects.add(new Subjects("234720-0003", "Instytucje sektora finansowego", "Alińska Agnieszka", DayOfWeek.MONDAY, LocalTime.of(17, 10), "G-110", 3.0));
        subjects.add(new Subjects("234720-0294", "Instytucje sektora finansowego", "Koleśnik Jan", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "G-105", 3.0));
        subjects.add(new Subjects("234750-0027", "Reasekuracja - aspekty aktuarialne", "Bijak Wojciech ", DayOfWeek.THURSDAY, LocalTime.of(17, 10), "C-2b", 3.0));
        subjects.add(new Subjects("234791-1028", "Managing Research and Development (R&D) in Transnati", "Kraj Kamil", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "G-114", 3.0));
        subjects.add(new Subjects("234881-0045", "Monetary Economics", "Brzoza-Brzezina Michał ", DayOfWeek.TUESDAY, LocalTime.of(9, 50), "B-12 komp.(Biblioteka)", 3.0));
        subjects.add(new Subjects("234900-0286", "Modelowanie wieloagentowe", "Kamiński Bogumił", DayOfWeek.THURSDAY, LocalTime.of(8, 00), "C-3a", 3.0));
        subjects.add(new Subjects("235100-0633", "Zarządzanie marką na rynku międzynarodowym", "Witek-Hajduk Marzanna", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "A-210", 3.0));
        subjects.add(new Subjects("235101-0633", "Brand Management on International Market", "Witek-Hajduk Marzanna", DayOfWeek.TUESDAY, LocalTime.of(19, 00), "A-210", 3.0));
        subjects.add(new Subjects("235110-1572", "Międzynarodowe strategie przedsiębiorstw", "Masłoń-Oracz Anna", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-214 CNJO", 3.0));
        subjects.add(new Subjects("235111-1992", "Firm Strategies in International Business", "Nowak Katarzyna", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "A-1", 3.0));
        subjects.add(new Subjects("235120-0389", "Organizacje pozarządowe", "Menkes Jerzy", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "G-324", 3.0));
        subjects.add(new Subjects("235140-1356", "Polityka migracyjna", "Pachocka Marta", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "G-115", 3.0));
        subjects.add(new Subjects("235141-1926", "Migration Polity", "Kleczewska Zofia", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "G-115", 3.0));
        subjects.add(new Subjects("235150-0485", "Porównania systemów gospodarczych-odmiany kapitalizm", "Rapacki Ryszard", DayOfWeek.THURSDAY, LocalTime.of(15, 20), "A-1", 3.0));
        subjects.add(new Subjects("235160-0149", "Usługi w gospodarce światowej", "Kuźnar Andżelika", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "G-225", 3.0));
        subjects.add(new Subjects("235200-1232", "Finanse behawioralne w praktyce", "Szyszka Adam", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "C-4a", 3.0));
        subjects.add(new Subjects("235201-1932", "Applied Behavioral Finance", "Rorat Tomasz", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "C-4a", 3.0));
        subjects.add(new Subjects("235220-0345", "Zarządzanie ryzykiem finansowym i instrumenty pochod", "Marciniak Zenon", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "C-4b", 3.0));
        subjects.add(new Subjects("235250-0152", "Gospodarka informacyjna", "Goliński Michał", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "A-1", 3.0));
        subjects.add(new Subjects("235280-0120", "Marketing z wykorzystaniem wyszukiwarek internetowy", "Doligalski Tymoteusz", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "Aula VII", 3.0));
        subjects.add(new Subjects("235300-1496", "Start-up technologiczny", "Kurowski Wojciech", DayOfWeek.FRIDAY, LocalTime.of(15, 20), "G-225", 3.0));
        subjects.add(new Subjects("235330-0385", "Trendy konsumenckie a strategie e-biznesu", "Mróz Bogdan", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "A-9", 3.0));
        subjects.add(new Subjects("235340-1016", "Zarządzanie łańcuchem dostaw w e-biznesie", "Nowicka Katarzyna", DayOfWeek.MONDAY, LocalTime.of(11, 40), "C-2a", 3.0));
        subjects.add(new Subjects("235350-0411", "Zarządzanie strategiczne IT", "Sobczak Andrzej", DayOfWeek.THURSDAY, LocalTime.of(19, 00), "Aula VII", 3.0));
        subjects.add(new Subjects("235370-1595", "Zarządzanie wiedzą", "Strojny Mariusz", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "A-219", 3.0));
        subjects.add(new Subjects("235380-1553", "Innowacje finansowe FinTech", "Maicki Piotr", DayOfWeek.MONDAY, LocalTime.of(13, 30), "C-5b", 3.0));
        subjects.add(new Subjects("235381-0969", "FinTech; Technology and Innovation in Financial Serv", "Roszkowska Paulina", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "C-5c", 3.0));
        subjects.add(new Subjects("235410-1027", "Współczesna teoria ekonometrii", "Serwa Dobromił", DayOfWeek.MONDAY, LocalTime.of(11, 40), "C-3e komp.", 3.0));
        subjects.add(new Subjects("235440-0646", "Warsztaty sporządzania pism w postępowaniach adminis", "Werner Aleksander", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "G-216 CNJO", 3.0));
        subjects.add(new Subjects("235450-0646", "Zawód doradcy podatkowego i etyka zawodowa", "Werner Aleksander", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "G-236", 3.0));
        subjects.add(new Subjects("235460-0229", "Propedeutyka rachunkowości", "Karmańska Anna", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "C-5b", 3.0));
        subjects.add(new Subjects("235510-1495", "Polityka energetyczna", "Księżopolski Krzysztof", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "G-012 (parter)", 3.0));
        subjects.add(new Subjects("235590-0257", "Polityka zdrowotna i finansowanie ochrony zdrowia", "Korporowicz Violetta", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "G-107", 3.0));
        subjects.add(new Subjects("235790-0517", "Organizacja i finansowanie własnej działalności gosp", "Skowronek-Mielczarek Anna", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "C-2e", 3.0));
        subjects.add(new Subjects("235920-0461", "Historia polskiej dyplomacji", "Podolska-Meducka Aldona", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "A-107", 3.0));
        subjects.add(new Subjects("236080-2835", "Cargo lotnicze", "Zagrajek Paweł", DayOfWeek.TUESDAY, LocalTime.of(19, 00), "A-1", 3.0));
        subjects.add(new Subjects("236090-0399", "Agencje ratingowe", "Niedziółka Paweł", DayOfWeek.MONDAY, LocalTime.of(17, 10), "G-223", 3.0));
        subjects.add(new Subjects("236121-0215", "Digital Media Economics (CEMS)", "Jung Bohdan", DayOfWeek.TUESDAY, LocalTime.of(16, 05), "C-2a", 3.0));
        subjects.add(new Subjects("236161-0207", "Strategic Analysis of European Markets (CEMS)", "Jarosiński Mirosław", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "C-2e", 3.0));
        subjects.add(new Subjects("236180-1025", "Nagrody Nobla-najnowsze trendy w ekonomii", "Bentkowska Katarzyna", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "G-215 CNJO", 3.0));
        subjects.add(new Subjects("236181-0578", "Transition in Central and Eastern Europe (CEMS)", "Słomka-Gołębiowska Agnieszka", DayOfWeek.MONDAY, LocalTime.of(9, 50), "C-2b", 3.0));
        subjects.add(new Subjects("236521-0082", "Cross-Cultural Management", "Czarzasty Jan", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "W-62", 3.0));
        subjects.add(new Subjects("236721-0217", "Lifestyles and New Product Development", "Janowska Anna A.", DayOfWeek.MONDAY, LocalTime.of(15, 20), "G-316", 3.0));
        subjects.add(new Subjects("236850-1109", "Międzynarodowe planowanie podatkowe", "Jamroży Marcin", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "G-230", 3.0));
        subjects.add(new Subjects("236860-0263", "Teoria i projektowanie badań reprezentacyjnych", "Kowalczyk Barbara", DayOfWeek.THURSDAY, LocalTime.of(8, 00), "G-114", 3.0));
        subjects.add(new Subjects("236960-0646", "Podatki pośrednie", "Werner Aleksander", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "G-012 (parter)", 3.0));
        subjects.add(new Subjects("237040-0640", "Psychologia reklamy", "Wójcik Jacek", DayOfWeek.MONDAY, LocalTime.of(11, 40), "C-1b", 3.0));
        subjects.add(new Subjects("237050-0391", "Public relations", "Mrówka Rafał", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "C-4c", 3.0));
        subjects.add(new Subjects("237100-0347", "Europejski rynek usług transportu lotniczego", "Marciszewska Elżbieta", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "G-223", 3.0));
        subjects.add(new Subjects("237780-0095", "E-usługi", "Dąbrowska Anna", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "A-208", 3.0));
        subjects.add(new Subjects("237850-0504", "Leasing", "Russel Piotr", DayOfWeek.WEDNESDAY, LocalTime.of(15, 20), "G-216 CNJO", 3.0));
        subjects.add(new Subjects("238030-0517", "Finansowanie małych i średnich przedsiębiorstw w Pol", "Skowronek-Mielczarek Anna", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "C-2e", 3.0));
        subjects.add(new Subjects("238070-0646", "Podatki bezpośrednie", "Werner Aleksander", DayOfWeek.TUESDAY, LocalTime.of(19, 00), "G-012 (parter)", 3.0));
        subjects.add(new Subjects("238201-0655", "Leadership: Managing, People, System and Self (CEMS)", "Wójcik Cezary", DayOfWeek.THURSDAY, LocalTime.of(9, 50), "C-2b", 3.0));
        subjects.add(new Subjects("238231-0699", "Business Process Outsourcing and Offshoring", "Radło Mariusz J.", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "G-115", 3.0));
        subjects.add(new Subjects("238290-0182", "Fair Trade a rozwój krajów Południa", "Zajaczkowski Małgorzata", DayOfWeek.MONDAY, LocalTime.of(13, 30), "G-225", 3.0));
        subjects.add(new Subjects("238400-0291", "Praktyczne inwestowanie w instrumenty futures na pla", "Krysiak Zbigniew", DayOfWeek.MONDAY, LocalTime.of(9, 50), "G-108 kom.", 3.0));
        subjects.add(new Subjects("238410-2746", "Realizacja projektu w formule corporate i project fi", "Lipski Mariusz", DayOfWeek.WEDNESDAY, LocalTime.of(19, 00), "C-1b", 3.0));
        subjects.add(new Subjects("238481-1272", "The application of quantitative methods in finance", "Pawłowska Małgorzata", DayOfWeek.FRIDAY, LocalTime.of(11, 40), "A-209", 3.0));
        subjects.add(new Subjects("238730-1017", "Zarządzanie sobą", "Klimek Jan", DayOfWeek.THURSDAY, LocalTime.of(8, 00), "A-218", 3.0));
        subjects.add(new Subjects("238740-0348", "Zarządzanie finansami w sektorze publicznym", "Marczakowska-Proczka Joanna", DayOfWeek.WEDNESDAY, LocalTime.of(9, 50), "G-223", 3.0));
        subjects.add(new Subjects("238791-1338", "Energy Security Economics", "Nyga-Łukaszewska Honorata ", DayOfWeek.TUESDAY, LocalTime.of(11, 40), "G-233", 3.0));
        subjects.add(new Subjects("238830-0136", "Ekonomia energii i polityka energetyczna", "Garbicz Marek", DayOfWeek.MONDAY, LocalTime.of(13, 30), "G-115", 3.0));
        subjects.add(new Subjects("238850-0375", "Stosunki międzynarodowe na Bliskim Wschodzie", "Modrzejewska-Leśniewska Joanna", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "A-8", 3.0));
        subjects.add(new Subjects("238860-0375", "Gospodarka i polityka Stanów Zjednoczonych i Kanady", "Modrzejewska-Leśniewska Joanna", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "A-9", 3.0));
        subjects.add(new Subjects("238910-0731", "Finanse muzułmańskie", "Masiukiewicz Piotr", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "G-224", 3.0));
        subjects.add(new Subjects("238940-1507", "Biznes lotniczy", "Hoszman Adam", DayOfWeek.TUESDAY, LocalTime.of(17, 10), "C-5b", 3.0));
        subjects.add(new Subjects("238941-1285", "Airline Business", "Krawczyk Grzegorz", DayOfWeek.TUESDAY, LocalTime.of(15, 20), "C-5b", 3.0));
        subjects.add(new Subjects("239010-1516", "Nadużycia na rynku finansowym", "Martysz Czesław", DayOfWeek.THURSDAY, LocalTime.of(19, 00), "G-103", 3.0));
        subjects.add(new Subjects("239210-2746", "Inwestycje kapitałowe i finansowe", "Lipski Mariusz", DayOfWeek.WEDNESDAY, LocalTime.of(17, 10), "C-5b", 3.0));
        subjects.add(new Subjects("239230-0382", "Historia rynków finansowych", "Morawski Wojciech", DayOfWeek.MONDAY, LocalTime.of(13, 30), "W-45", 3.0));
        subjects.add(new Subjects("239320-1156", "Zarządzanie ryzykiem bankowym (z wykorzystaniem nar", "Orzechowski Arkadiusz", DayOfWeek.WEDNESDAY, LocalTime.of(11, 40), "G-108 kom.", 3.0));
        subjects.add(new Subjects("239411-1263", "History of the Middle-East", "Łazor Jerzy", DayOfWeek.FRIDAY, LocalTime.of(13, 30), "A-213", 3.0));
        subjects.add(new Subjects("239481-0637", "Global Startup Ecosystem CEMS", "Wojtysiak-Kotlarski Marcin", DayOfWeek.MONDAY, LocalTime.of(15, 20), "C-2e", 3.0));
        subjects.add(new Subjects("239720-1326", "Ekonomia  sportu", "Skrok Łukasz", DayOfWeek.THURSDAY, LocalTime.of(13, 30), "G-114", 3.0));
        subjects.add(new Subjects("239901-1349", "China in the Global Economy", "Mccaleb Agnieszka", DayOfWeek.TUESDAY, LocalTime.of(13, 30), "C-5c", 3.0));
        subjects.add(new Subjects("239920-0628", "Ucieczka przed podatkiem. Formy, prawne ograniczenia", "Mccaleb Agnieszka", DayOfWeek.WEDNESDAY, LocalTime.of(13, 30), "A-210", 3.0));
        subjects.add(new Subjects("239931-0190", "FinTech and Commerce Startups with Mastercard (CEMS)", "Pindelski Mikołaj", DayOfWeek.WEDNESDAY, LocalTime.of(14, 25), "C-2e", 3.0));
        subjects.add(new Subjects("239951-0440", "Development of Digital Economy 4.0", "Paprocki Wojciech", DayOfWeek.THURSDAY, LocalTime.of(11, 40), "C-3e komp.", 3.0));

        writeObjectToFile(subjects, "subjects.txt");

        List<Courses> courses = new ArrayList<>();

        courses.add(new Courses("21010", "Historia myśli ekonomicznej", 4.5));
        courses.add(new Courses("21011", "Prawo gospodarcze", 4.5));
        courses.add(new Courses("22209", "Ekonomia menedżerska", 4.5));
        courses.add(new Courses("22212", "Ekonomia rozwoju", 4.5));
        courses.add(new Courses("22213", "Ekonomia sektora publicznego", 4.5));
        courses.add(new Courses("22038", "Polityka pieniężna", 3.0));
        courses.add(new Courses("22053", "Rachunkowość zarządcza", 3.0));
        courses.add(new Courses("22204", "Ekonometria finansowa I", 3.0));
        courses.add(new Courses("22216", "Etyka w biznesie", 3.0));
        courses.add(new Courses("22225", "Inżynieria finansowa", 3.0));
        courses.add(new Courses("22249", "Rachunek kosztów", 3.0));
        courses.add(new Courses("22043", "Portfel inwestycyjny", 4.5));
        courses.add(new Courses("22074", "Zaawansowana rachunkowość finansowa", 4.5));
        courses.add(new Courses("22075", "Zarządzanie bankiem", 4.5));
        courses.add(new Courses("22246", "Prawo finansowe i podatkowe", 4.5));
        courses.add(new Courses("22249", "Rachunek kosztów", 3.0));
        courses.add(new Courses("22068", "Ubezpieczenia społeczne", 3.0));
        courses.add(new Courses("22096", "Postępowanie sądowo-administracyjne", 3.0));
        courses.add(new Courses("22133", "Międzynarodowe finanse przedsiębiorstw", 3.0));
        courses.add(new Courses("23006", "Analiza techniczna i fundamentalna", 3.0));
        courses.add(new Courses("23091", "Polityka budżetowa", 3.0));
        courses.add(new Courses("23115", "Rachunkowość w banku", 3.0));
        courses.add(new Courses("23116", "Rachunkowość w zakładzie ubezpieczeń", 3.0));
        courses.add(new Courses("23117", "Reasekuracja", 3.0));
        courses.add(new Courses("23123", "Rynek instrumentów pochodnych", 3.0));
        courses.add(new Courses("23216", "Postępowanie podatkowe", 3.0));
        courses.add(new Courses("23258", "Teoria i polityka kursów walutowych", 3.0));
        courses.add(new Courses("23265", "Fuzje i przejęcia przedsiębiorstw", 3.0));
        courses.add(new Courses("23306", "Budżet samorządowy", 3.0));
        courses.add(new Courses("23335", "Kryzysy finansowe i stabilność finansowa", 3.0));
        courses.add(new Courses("23349", "Optymalizacja podatkowa", 3.0));
        courses.add(new Courses("23358", "Prawo celne", 3.0));
        courses.add(new Courses("23359", "Prawo karne skarbowe", 3.0));
        courses.add(new Courses("23368", "Przygotowanie projektów finansowanych ze środków U", 3.0));
        courses.add(new Courses("23371", "Regulacje i nadzór nad rynkami finansowymi", 3.0));
        courses.add(new Courses("23376", "Ryzyko w zakładzie ubezpieczeń", 3.0));
        courses.add(new Courses("23391", "Struktura kapitału w przedsiębiorstwie", 3.0));
        courses.add(new Courses("23397", "Teoria ryzyka", 3.0));
        courses.add(new Courses("23404", "Zaawansowana bankowość inwestycyjna", 3.0));
        courses.add(new Courses("23410", "Zarządzanie portfelem kredytowym banku", 3.0));
        courses.add(new Courses("23414", "Zarządzanie ryzykiem finansowym w przedsiębiorstwi", 3.0));
        courses.add(new Courses("23415", "Zarządzanie ryzykiem rynkowym i operacyjnym", 3.0));
        courses.add(new Courses("23449", "Zarządzanie finansami (ACCA-P)", 3.0));
        courses.add(new Courses("23472", "Instytucje sektora finansowego", 3.0));
        courses.add(new Courses("23544", "Warsztaty sporządzania pism w postępowaniach adminis", 3.0));
        courses.add(new Courses("23545", "Zawód doradcy podatkowego i etyka zawodowa", 3.0));
        courses.add(new Courses("23546", "Propedeutyka rachunkowości", 3.0));
        courses.add(new Courses("23685", "Międzynarodowe planowanie podatkowe", 3.0));
        courses.add(new Courses("23696", "Podatki pośrednie", 3.0));
        courses.add(new Courses("23807", "Podatki bezpośrednie", 3.0));
        courses.add(new Courses("12011", "Badania marketingowe", 3.0));
        courses.add(new Courses("12048", "Prawo międzynarodowe publiczne", 3.0));
        courses.add(new Courses("12049", "Prawo pracy", 3.0));
        courses.add(new Courses("12070", "Zarządzanie projektami", 3.0));
        courses.add(new Courses("12092", "Marketing międzynarodowy", 3.0));
        courses.add(new Courses("12092", "International Marketing", 3.0));
        courses.add(new Courses("12104", "Biznesplan", 3.0));
        courses.add(new Courses("12111", "Fundusze strukturalne Unii Europejskiej", 3.0));
        courses.add(new Courses("12139", "Zarządzanie projektami Unii Europejskiej", 3.0));
        courses.add(new Courses("12140", "Management in International Business", 3.0));
        courses.add(new Courses("12150", "Rynek kapitałowy", 3.0));
        courses.add(new Courses("13066", "Prawo podatkowe", 3.0));
        courses.add(new Courses("21013", "Ekonomia", 3.0));
        courses.add(new Courses("22028", "International Marketing", 3.0));
        courses.add(new Courses("22034", "Mikroekonometria", 3.0));
        courses.add(new Courses("22034", "Microeconometrics", 3.0));
        courses.add(new Courses("22043", "Investment portfolio", 3.0));
        courses.add(new Courses("22044", "Postępowanie nabywców na rynku", 3.0));
        courses.add(new Courses("22044", "Customer Behavior", 3.0));
        courses.add(new Courses("22050", "Entrepreneurship", 3.0));
        courses.add(new Courses("22057", "Statystyczne metody wielowymiarowej analizy", 3.0));
        courses.add(new Courses("22059", "Statystyka społeczna", 3.0));
        courses.add(new Courses("22062", "Sztuczna inteligencja", 3.0));
        courses.add(new Courses("22074", "Advanced Financial Accounting", 3.0));
        courses.add(new Courses("22075", "Bank management", 3.0));
        courses.add(new Courses("22075", "Zarządzanie bankiem (blended learning)", 3.0));
        courses.add(new Courses("22077", "Zarządzanie logistyczne", 3.0));
        courses.add(new Courses("22077", "Logistics Management", 3.0));
        courses.add(new Courses("22082", "Zarządzanie wartością przedsiębiorstwa", 3.0));
        courses.add(new Courses("22133", "International Corporate Finance", 3.0));
        courses.add(new Courses("22134", "Globalizacja i regionalizacja w stosunkach międzyn", 3.0));
        courses.add(new Courses("22137", "Kulturowe uwarunkowania biznesu międzynarodowego", 3.0));
        courses.add(new Courses("22147", "Zarządzanie operacyjne", 3.0));
        courses.add(new Courses("22147", "Operations Management", 3.0));
        courses.add(new Courses("22148", "Metody statystyczne II", 3.0));
        courses.add(new Courses("22148", "Statistical Methods II (QEM)", 3.0));
        courses.add(new Courses("22164", "Technologiczne uwarunkowania biznesu międzynarodoweg", 3.0));
        courses.add(new Courses("22165", "Instytucjonalne uwarunkowania biznesu międzynarodowe", 3.0));
        courses.add(new Courses("22200", "Algebra i analiza matematyczna", 3.0));
        courses.add(new Courses("22204", "Financial Econometrics I", 3.0));
        courses.add(new Courses("22206", "Ekonometria szeregów czasowych", 3.0));
        courses.add(new Courses("22208", "Ekonomia instytucjonalna", 3.0));
        courses.add(new Courses("22210", "Ekonomia międzynarodowa (zaawansowana)", 3.0));
        courses.add(new Courses("22211", "Ekonomia pracy", 3.0));
        courses.add(new Courses("22214", "Ekonomia środowiska", 3.0));
        courses.add(new Courses("22215", "Mathematical economics and optimal control theory", 3.0));
        courses.add(new Courses("22223", "Informacyjne systemy zarządzania", 3.0));
        courses.add(new Courses("22226", "Inżynieria oprogramowania", 3.0));
        courses.add(new Courses("22229", "Advanced Macroeconomics", 3.0));
        courses.add(new Courses("22232", "Introduction to Probability Theory and Stochastic Pr", 3.0));
        courses.add(new Courses("22234", "Międzynarodowe rynki finansowe", 3.0));
        courses.add(new Courses("22237", "Mikroekonomia (zaawansowana)", 3.0));
        courses.add(new Courses("22237", "Advanced Microeconomics (QEM)", 3.0));
        courses.add(new Courses("22245", "Poland in the European Union", 3.0));
        courses.add(new Courses("22246", "Financial and Tax Law", 3.0));
        courses.add(new Courses("22247", "Prawo handlowe", 3.0));
        courses.add(new Courses("22249", "Cost Accounting (ACCA)", 3.0));
        courses.add(new Courses("22258", "Rachunek prawdopodobieństwa i procesy stochastyczn", 3.0));
        courses.add(new Courses("22260", "Zarządzanie kapitałem ludzkim", 3.0));
        courses.add(new Courses("22261", "Zarządzanie procesami", 3.0));
        courses.add(new Courses("22262", "Zarządzanie strategiczne", 3.0));
        courses.add(new Courses("22262", "Strategic Management", 3.0));
        courses.add(new Courses("22280", "Nieklasyczne metody optymalizacj", 3.0));
        courses.add(new Courses("22281", "Rachunkowość zarządcza i rachunek kosztów", 3.0));
        courses.add(new Courses("22281", "Management and Cost Accounting", 3.0));
        courses.add(new Courses("22294", "Teoria gier", 3.0));
        courses.add(new Courses("22295", "Ekonometria przestrzenna", 3.0));
        courses.add(new Courses("22297", "Teoria zarządzania", 3.0));
        courses.add(new Courses("22298", "Prawo cywilne", 3.0));
        courses.add(new Courses("22305", "Makroekonomia zaawansowana I", 3.0));
        courses.add(new Courses("22309", "Big data", 3.0));
        courses.add(new Courses("22320", "Dyplomacja gospodarcza", 3.0));
        courses.add(new Courses("22323", "Ekonomia innowacji i zarządzanie innowacjami", 3.0));
        courses.add(new Courses("22324", "Środowisko naturalne i energia: konflikty i współpra", 3.0));
        courses.add(new Courses("22324", "Natural Environment and Energy: International Confl", 3.0));
        courses.add(new Courses("22325", "Ekonomia Behawioralna w e-biznesie", 3.0));
        courses.add(new Courses("22326", "Ekonomia niedoskonałej konkurencji", 3.0));
        courses.add(new Courses("22327", "Technologie cyfrowe w relacjach gospodarczych", 3.0));
        courses.add(new Courses("22328", "Finansowanie i wycena spółek technologicznych", 3.0));
        courses.add(new Courses("22328", "Financing and Valuation of High-Tech Companies", 3.0));
        courses.add(new Courses("22329", "Strategie i modele e-biznesu", 3.0));
        courses.add(new Courses("22331", "Analiza i zastosowania sieci społecznych w interne", 3.0));
        courses.add(new Courses("22332", "Globalne ubóstwo, niedorozwój i rozwój", 3.0));
        courses.add(new Courses("22335", "Prawo e-biznesu", 3.0));
        courses.add(new Courses("22337", "Nowe technologie w marketingu", 3.0));
        courses.add(new Courses("22339", "Strategiczne zarządzanie projektami", 3.0));
        courses.add(new Courses("22345", "Statystyczne metody analizy ubóstwa, wykluczenia spo", 3.0));
        courses.add(new Courses("22349", "Statystyczne reguły decyzyjne", 3.0));
        courses.add(new Courses("22350", "Zarządzanie finansami na rynku międzynarodowym", 3.0));
        courses.add(new Courses("22396", "Podstawy zarządzania projektami", 3.0));
        courses.add(new Courses("22438", "Efektywne zarządzanie IT w przedsiębiorstwie", 3.0));
        courses.add(new Courses("22439", "Obliczenia i przetwarzanie danych w chmurze-cloud co", 3.0));
        courses.add(new Courses("22441", "Style życia usługi czasu wolnego", 3.0));
        courses.add(new Courses("22452", "Finanse i rachunkowość menedżerska", 3.0));
        courses.add(new Courses("22455", "Logistyka", 3.0));
        courses.add(new Courses("22456", "Prawne uwarunkwania pracy menedżera", 3.0));
        courses.add(new Courses("22502", "Wprowadzenie do zarządzania projektami", 3.0));
        courses.add(new Courses("22505", "Rachunkowość projektów", 3.0));
        courses.add(new Courses("22506", "Podstawy organizacji i zarządzania", 3.0));
        courses.add(new Courses("22511", "Zarządzanie przedsiębiorstwem", 3.0));
        courses.add(new Courses("22513", "Zarzadzanie procesami biznesowymi", 3.0));
        courses.add(new Courses("22602", "Analiza aktywności projektów", 3.0));
        courses.add(new Courses("22603", "Controling i audyt finansowy przedsiębiorstwa", 3.0));
        courses.add(new Courses("22604", "Diagnostyka finansowa przedsiębiorstwa", 3.0));
        courses.add(new Courses("22606", "Finanse korporacji", 3.0));
        courses.add(new Courses("22607", "Tradycyjne i alternatywne źródła finansowania przedi", 3.0));
        courses.add(new Courses("22608", "Rachunkowość finansowa i menedżerska", 3.0));
        courses.add(new Courses("22610", "Zastosowania inżynierii finansowej", 3.0));
        courses.add(new Courses("22611", "Zintegrowane zarządzanie ryzykiem - ERM", 3.0));
        courses.add(new Courses("22615", "Przedsiębiorczość - perspektywa startupu", 3.0));
        courses.add(new Courses("22615", "Startup entrepreneurship", 3.0));
        courses.add(new Courses("23012", "Komunikacja społeczna", 3.0));
        courses.add(new Courses("23020", "Ekonometria bayesowska", 3.0));
        courses.add(new Courses("23024", "Ekonometryczne modele nieliniowe", 3.0));
        courses.add(new Courses("23030", "Europejski system transportowy", 3.0));
        courses.add(new Courses("23046", "Kierowanie zespołem projektowym", 3.0));
        courses.add(new Courses("23051", "Logistyka dystrybucji", 3.0));
        courses.add(new Courses("23054", "Marketing na rynku instytucjonalnym", 3.0));
        courses.add(new Courses("23054", "Business-to-Business Marketing", 3.0));
        courses.add(new Courses("23057", "Marketing usług transportowych", 3.0));
        courses.add(new Courses("23071", "Międzynarodowe rynki transportowe", 3.0));
        courses.add(new Courses("23072", "Modele i prognozy demograficzne", 3.0));
        courses.add(new Courses("23082", "Organizacja projektowa", 3.0));
        courses.add(new Courses("23088", "Podstawy informacyjne marketingu", 3.0));
        courses.add(new Courses("23109", "Proces motywowania pracowników", 3.0));
        courses.add(new Courses("23121", "Restrukturyzacja przedsiębiorstwa", 3.0));
        courses.add(new Courses("23123", "Derivatives Market", 3.0));
        courses.add(new Courses("23138", "Strategia personalna przedsiębiorstwa", 3.0));
        courses.add(new Courses("23142", "Strategie konkurencji i rozwoju polskich przedsięb", 3.0));
        courses.add(new Courses("23145", "Systemy baz danych II", 3.0));
        courses.add(new Courses("23151", "Prawne uwarunkowania prowadzenia własnego biznesu", 3.0));
        courses.add(new Courses("23156", "Teoria opodatkowania", 3.0));
        courses.add(new Courses("23167", "Konwersatorium z ekonomii", 3.0));
        courses.add(new Courses("23176", "Marketing dóbr luksusowych i o charakterze symbolic", 3.0));
        courses.add(new Courses("23188", "Alternatywny pieniądz", 3.0));
        courses.add(new Courses("23200", "Międzynarodowe strategie kooperacji przedsiębiorst", 3.0));
        courses.add(new Courses("23208", "Techniki aktuarialne w praktyce ubezpieczeń na życie", 3.0));
        courses.add(new Courses("23230", "Business Strategies for Central and Eastern Europe", 3.0));
        courses.add(new Courses("23246", "National Innovation Systems in the World Economy", 3.0));
        courses.add(new Courses("23260", "Analiza strategiczna przedsiębiorstwa w wymiarze m", 3.0));
        courses.add(new Courses("23265", "Mergers and Acquisitions of Enterprises", 3.0));
        courses.add(new Courses("23277", "Partnerstwo publiczno-prywatne", 3.0));
        courses.add(new Courses("23290", "Strategic Analysis of European Markets", 3.0));
        courses.add(new Courses("23301", "Analiza koniunktury i badanie rynków zagranicznych", 3.0));
        courses.add(new Courses("23303", "Analiza wzorów konsumpcji gospodarstw domowych", 3.0));
        courses.add(new Courses("23304", "Analizy rynku metodami ilościowymi", 3.0));
        courses.add(new Courses("23307", "Business Intelligence", 3.0));
        courses.add(new Courses("23318", "Ekonometria finansowa II", 3.0));
        courses.add(new Courses("23320", "Ekonomia polityczna", 3.0));
        courses.add(new Courses("23324", "Euromarketing", 3.0));
        courses.add(new Courses("23331", "Jakościowe badania marketingowe", 3.0));
        courses.add(new Courses("23346", "General Equilibrium Frameworks", 3.0));
        courses.add(new Courses("23351", "Plan zarządzania nieruchomością", 3.0));
        courses.add(new Courses("23364", "Problemy demograficzne świata", 3.0));
        courses.add(new Courses("23385", "Statystyka aktuarialna i teoria ryzyka", 3.0));
        courses.add(new Courses("23389", "Strategie kooperacji przedsiębiorstw", 3.0));
        courses.add(new Courses("23404", "Advanced Investment Banking", 3.0));
        courses.add(new Courses("23406", "Zaawansowane modelowanie symulacyjne", 3.0));
        courses.add(new Courses("23408", "Zarządzanie innowacjami w przedsiębiorstwie", 3.0));
        courses.add(new Courses("23411", "Zarządzanie projektami informatycznymi", 3.0));
        courses.add(new Courses("23414", "Corporate Financial Risk Management", 3.0));
        courses.add(new Courses("23430", "Negotiations", 3.0));
        courses.add(new Courses("23461", "Transformacja systemowa Rosji", 3.0));
        courses.add(new Courses("23475", "Reasekuracja - aspekty aktuarialne", 3.0));
        courses.add(new Courses("23479", "Managing Research and Development (R&D) in Transnati", 3.0));
        courses.add(new Courses("23488", "Monetary Economics", 3.0));
        courses.add(new Courses("23490", "Modelowanie wieloagentowe", 3.0));
        courses.add(new Courses("23510", "Zarządzanie marką na rynku międzynarodowym", 3.0));
        courses.add(new Courses("23510", "Brand Management on International Market", 3.0));
        courses.add(new Courses("23511", "Międzynarodowe strategie przedsiębiorstw", 3.0));
        courses.add(new Courses("23511", "Firm Strategies in International Business", 3.0));
        courses.add(new Courses("23512", "Organizacje pozarządowe", 3.0));
        courses.add(new Courses("23514", "Polityka migracyjna", 3.0));
        courses.add(new Courses("23514", "Migration Polity", 3.0));
        courses.add(new Courses("23515", "Porównania systemów gospodarczych-odmiany kapitalizm", 3.0));
        courses.add(new Courses("23516", "Usługi w gospodarce światowej", 3.0));
        courses.add(new Courses("23520", "Finanse behawioralne w praktyce", 3.0));
        courses.add(new Courses("23520", "Applied Behavioral Finance", 3.0));
        courses.add(new Courses("23522", "Zarządzanie ryzykiem finansowym i instrumenty pochod", 3.0));
        courses.add(new Courses("23525", "Gospodarka informacyjna", 3.0));
        courses.add(new Courses("23528", "Marketing z wykorzystaniem wyszukiwarek internetowy", 3.0));
        courses.add(new Courses("23530", "Start-up technologiczny", 3.0));
        courses.add(new Courses("23533", "Trendy konsumenckie a strategie e-biznesu", 3.0));
        courses.add(new Courses("23534", "Zarządzanie łańcuchem dostaw w e-biznesie", 3.0));
        courses.add(new Courses("23535", "Zarządzanie strategiczne IT", 3.0));
        courses.add(new Courses("23537", "Zarządzanie wiedzą", 3.0));
        courses.add(new Courses("23538", "Innowacje finansowe FinTech", 3.0));
        courses.add(new Courses("23538", "FinTech; Technology and Innovation in Financial Serv", 3.0));
        courses.add(new Courses("23541", "Współczesna teoria ekonometrii", 3.0));
        courses.add(new Courses("23551", "Polityka energetyczna", 3.0));
        courses.add(new Courses("23559", "Polityka zdrowotna i finansowanie ochrony zdrowia", 3.0));
        courses.add(new Courses("23579", "Organizacja i finansowanie własnej działalności gosp", 3.0));
        courses.add(new Courses("23592", "Historia polskiej dyplomacji", 3.0));
        courses.add(new Courses("23608", "Cargo lotnicze", 3.0));
        courses.add(new Courses("23609", "Agencje ratingowe", 3.0));
        courses.add(new Courses("23612", "Digital Media Economics (CEMS)", 3.0));
        courses.add(new Courses("23616", "Strategic Analysis of European Markets (CEMS)", 3.0));
        courses.add(new Courses("23618", "Nagrody Nobla-najnowsze trendy w ekonomii", 3.0));
        courses.add(new Courses("23618", "Transition in Central and Eastern Europe (CEMS)", 3.0));
        courses.add(new Courses("23652", "Cross-Cultural Management", 3.0));
        courses.add(new Courses("23672", "Lifestyles and New Product Development", 3.0));
        courses.add(new Courses("23686", "Teoria i projektowanie badań reprezentacyjnych", 3.0));
        courses.add(new Courses("23704", "Psychologia reklamy", 3.0));
        courses.add(new Courses("23705", "Public relations", 3.0));
        courses.add(new Courses("23710", "Europejski rynek usług transportu lotniczego", 3.0));
        courses.add(new Courses("23778", "E-usługi", 3.0));
        courses.add(new Courses("23785", "Leasing", 3.0));
        courses.add(new Courses("23803", "Finansowanie małych i średnich przedsiębiorstw w Pol", 3.0));
        courses.add(new Courses("23820", "Leadership: Managing, People, System and Self (CEMS)", 3.0));
        courses.add(new Courses("23823", "Business Process Outsourcing and Offshoring", 3.0));
        courses.add(new Courses("23829", "Fair Trade a rozwój krajów Południa", 3.0));
        courses.add(new Courses("23840", "Praktyczne inwestowanie w instrumenty futures na pla", 3.0));
        courses.add(new Courses("23841", "Realizacja projektu w formule corporate i project fi", 3.0));
        courses.add(new Courses("23848", "The application of quantitative methods in finance", 3.0));
        courses.add(new Courses("23873", "Zarządzanie sobą", 3.0));
        courses.add(new Courses("23874", "Zarządzanie finansami w sektorze publicznym", 3.0));
        courses.add(new Courses("23879", "Energy Security Economics", 3.0));
        courses.add(new Courses("23883", "Ekonomia energii i polityka energetyczna", 3.0));
        courses.add(new Courses("23885", "Stosunki międzynarodowe na Bliskim Wschodzie", 3.0));
        courses.add(new Courses("23886", "Gospodarka i polityka Stanów Zjednoczonych i Kanady", 3.0));
        courses.add(new Courses("23891", "Finanse muzułmańskie", 3.0));
        courses.add(new Courses("23894", "Biznes lotniczy", 3.0));
        courses.add(new Courses("23894", "Airline Business", 3.0));
        courses.add(new Courses("23901", "Nadużycia na rynku finansowym", 3.0));
        courses.add(new Courses("23921", "Inwestycje kapitałowe i finansowe", 3.0));
        courses.add(new Courses("23923", "Historia rynków finansowych", 3.0));
        courses.add(new Courses("23932", "Zarządzanie ryzykiem bankowym (z wykorzystaniem nar", 3.0));
        courses.add(new Courses("23941", "History of the Middle-East", 3.0));
        courses.add(new Courses("23948", "Global Startup Ecosystem CEMS", 3.0));
        courses.add(new Courses("23972", "Ekonomia  sportu", 3.0));
        courses.add(new Courses("23990", "China in the Global Economy", 3.0));
        courses.add(new Courses("23992", "Ucieczka przed podatkiem. Formy, prawne ograniczenia", 3.0));
        courses.add(new Courses("23993", "FinTech and Commerce Startups with Mastercard (CEMS)", 3.0));
        courses.add(new Courses("23995", "Development of Digital Economy 4.0", 3.0));

        writeObjectToFile(courses, "courses.txt");


    }

    public static void writeObjectToFile(Object serObj, String path) {
        try (FileOutputStream fileOutputStream = new FileOutputStream(path);
             ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream);) {
            objectOutputStream.writeObject(serObj);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
